import type { BadgeDefinition } from "@/types/badges";

export const badges: BadgeDefinition[] = [
  // ── PROGRESS ──────────────────────────────────────────
  {
    id: "first_steps",
    name: "First Steps",
    description: "Complete your first chapter!",
    emoji: "🐣",
    category: "progress",
    conditions: [{ type: "chapters_completed", value: 1 }],
    sortOrder: 1,
  },
  {
    id: "city_explorer",
    name: "City Explorer",
    description: "Complete the City Streets chapter",
    emoji: "🏙️",
    category: "progress",
    conditions: [{ type: "chapter_completed", chapterId: 1 }],
    sortOrder: 2,
  },
  {
    id: "park_ranger",
    name: "Park Ranger",
    description: "Complete the Park of Possibilities",
    emoji: "🌳",
    category: "progress",
    conditions: [{ type: "chapter_completed", chapterId: 2 }],
    sortOrder: 3,
  },
  {
    id: "farm_friend",
    name: "Farm Friend",
    description: "Complete the Farmlands of Plenty",
    emoji: "🌾",
    category: "progress",
    conditions: [{ type: "chapter_completed", chapterId: 3 }],
    sortOrder: 4,
  },
  {
    id: "forest_scout",
    name: "Forest Scout",
    description: "Complete the Countryside Forest",
    emoji: "🌲",
    category: "progress",
    conditions: [{ type: "chapter_completed", chapterId: 4 }],
    sortOrder: 5,
  },
  {
    id: "jungle_hero",
    name: "Jungle Hero",
    description: "Complete the final chapter and bring Alex home!",
    emoji: "🦜",
    category: "progress",
    conditions: [{ type: "chapter_completed", chapterId: 5 }],
    sortOrder: 6,
  },
  {
    id: "halfway_there",
    name: "Halfway There",
    description: "Complete 3 chapters",
    emoji: "⭐",
    category: "progress",
    conditions: [{ type: "chapters_completed", value: 3 }],
    sortOrder: 7,
  },
  {
    id: "quest_complete",
    name: "Quest Complete",
    description: "Finish all 5 chapters of Alex's Quest!",
    emoji: "🏆",
    category: "progress",
    conditions: [{ type: "all_chapters_completed" }],
    sortOrder: 8,
  },

  // ── MASTERY ──────────────────────────────────────────
  {
    id: "pronunciation_pro",
    name: "Pronunciation Pro",
    description: "Score 90%+ pronunciation on a chapter",
    emoji: "🎤",
    category: "mastery",
    conditions: [{ type: "pronunciation_avg", value: 90 }],
    sortOrder: 14,
  },
  {
    id: "sound_master",
    name: "Sound Master",
    description: "Clear all problem phonemes",
    emoji: "🔊",
    category: "mastery",
    conditions: [{ type: "problem_phonemes_zero" }],
    sortOrder: 15,
  },

  // ── STREAK ───────────────────────────────────────────
  {
    id: "streak_3",
    name: "On a Roll",
    description: "Play 3 days in a row!",
    emoji: "🔥",
    category: "streak",
    conditions: [{ type: "streak", value: 3 }],
    sortOrder: 20,
  },
  {
    id: "streak_7",
    name: "Week Warrior",
    description: "Play 7 days in a row!",
    emoji: "🔥",
    category: "streak",
    conditions: [{ type: "streak", value: 7 }],
    sortOrder: 21,
  },
  {
    id: "streak_14",
    name: "Two-Week Streak",
    description: "Play 14 days in a row!",
    emoji: "💪",
    category: "streak",
    conditions: [{ type: "streak", value: 14 }],
    sortOrder: 22,
  },
  {
    id: "streak_30",
    name: "Monthly Legend",
    description: "Play 30 days in a row!",
    emoji: "🏅",
    category: "streak",
    conditions: [{ type: "streak", value: 30 }],
    sortOrder: 23,
  },

  // ── SPECIAL ──────────────────────────────────────────
  {
    id: "first_try_hero",
    name: "First Try Hero",
    description: "Pass every question in a chapter on the first try",
    emoji: "🎯",
    category: "special",
    conditions: [{ type: "first_try_chapter" }],
    sortOrder: 30,
  },
  {
    id: "rival_crusher",
    name: "Rival Crusher",
    description: "Score 90%+ on a rival question",
    emoji: "⚔️",
    category: "special",
    conditions: [{ type: "question_score", value: 90 }],
    sortOrder: 31,
    secret: true,
  },
];

export const getBadgeById = (id: string): BadgeDefinition | undefined =>
  badges.find((b) => b.id === id);
